Proj 1 vector operations
andreyi91/cpp-projects pull request #4
Opened 2020-10-01 13:53 UTC by andreyi91

2020-10-15 21:33 UTC, SweetWeakness requested changes

2020-10-15 21:33 UTC, SweetWeakness commented on vector_ops/src/vector_ops.h
> +    c.push_back(a[i] + b[i]);
создавайте вектор определенной размерности и приравнивайте его элементы (без пушбеков, в дальнейших операторах аналогично)

2020-10-15 21:33 UTC, SweetWeakness commented on vector_ops/src/vector_ops.h
> +  double k = a[0] / b[0];
а если ноль?

2020-10-15 21:33 UTC, SweetWeakness commented on vector_ops/src/vector_ops.h
> +using std::cout;
вы же их не используете

2020-10-29 02:08 UTC, Costello1329 approved these changes
.

2020-10-29 02:09 UTC, Costello1329 commented
Конфликты. Исправьте и вмерджте плиз

2020-10-29 12:42 UTC, merged